logs:
  dir_logs: logs/med/minhmul_att_train_imagenet_augment_h200_g4_relu
vqa:
    dataset: VQA
    dir: data/vqa_med
    trainsplit: train
    nans: 1700
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/raw/vqa_med/preprocessed/
    arch: fbresnet152
    mode: att
    size: 448
model:
    arch: MinhmulAtt
    dim_v: 2048
    dim_q: 2400
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.5
        fixed_emb: False
    attention:
        nb_glimpses: 4
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: leaky_relu
        activation_q: leaky_relu
        activation_mm: leaky_relu
    fusion:
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: leaky_relu
        activation_q: leaky_relu
    classif:
        activation: leaky_relu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 1
    epochs: 100
