arch: null
batch_size: 1024
bert_model: bert-base-multilingual-uncased
dir_logs: logs/breast/minhmul_noatt_train_selu
epochs: 70
evaluate: false
help_opt: false
is_augment_image: '1'
learning_rate: null
path_opt: options/breast/minhmul_noatt_train_selu.yaml
print_freq: 10
resume: ''
save_all_from: null
save_model: true
st_dropout: null
st_fixed_emb: null
st_type: null
start_epoch: 0
vqa_trainsplit: train
workers: 4
