coco:
  arch: resnet152_breast
  dir: data/raw/breast-cancer/preprocessed/WSI
  mode: noatt
  size: 448
logs:
  dir_logs: logs/breast/minhmul_noatt_train_selu
model:
  arch: MinhmulNoAtt
  classif:
    activation: selu
    dropout: 0.5
  fusion:
    activation_q: selu
    activation_v: selu
    dim_h: 1200
    dim_q: 2400
    dim_v: 2048
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 1024
  epochs: 70
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_breast
  maxlength: 26
  minwcount: 0
  nans: 844
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
