arch: null
batch_size: null
dir_logs: null
epochs: null
evaluate: false
help_opt: false
learning_rate: null
path_opt: options/tools/minhmul_noatt_train.yaml
print_freq: 2
resume: ''
save_all_from: null
save_model: true
st_dropout: null
st_fixed_emb: null
st_type: null
start_epoch: 0
vqa_trainsplit: train
workers: 2
