coco:
  arch: resnet152_tools
  dir: data/raw/m2cai16-tool-locations/preprocessed/segmentation
  mode: noatt
  size: 448
logs:
  dir_logs: logs/tools/mutan_noatt_train
model:
  arch: MutanNoAtt
  classif:
    dropout: 0.5
  fusion:
    R: 10
    activation_q: tanh
    activation_v: tanh
    dim_h: 360
    dim_hq: 360
    dim_hv: 360
    dim_mm: 360
    dim_q: 2400
    dim_v: 2048
    dropout_hq: 0
    dropout_hv: 0
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 128
  epochs: 100
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_tools
  maxlength: 26
  minwcount: 0
  nans: 14
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
