coco:
  arch: fbresnet152torch
  dir: data/coco
  mode: noatt
logs:
  dir_logs: logs/vqa/mutan_noatt_train
model:
  arch: MutanNoAtt
  classif:
    dropout: 0.5
  fusion:
    R: 10
    activation_q: tanh
    activation_v: tanh
    dim_h: 360
    dim_hq: 360
    dim_hv: 360
    dim_mm: 360
    dim_q: 2400
    dim_v: 2048
    dropout_hq: 0
    dropout_hv: 0
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 512
  epochs: 100
  lr: 1.0e-05
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa
  maxlength: 26
  minwcount: 0
  nans: 3
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
