coco:
  arch: resnet152_tools
  dir: data/raw/m2cai16-tool-locations/preprocessed/segmentation
  mode: att
  size: 448
logs:
  dir_logs: logs/tools/minhmul_att_train_relu
model:
  arch: MinhmulAtt
  attention:
    activation_mm: relu
    activation_q: relu
    activation_v: relu
    dim_h: 1200
    dim_mm: 1200
    dim_q: 1200
    dim_v: 1200
    dropout_mm: 0.5
    dropout_q: 0.5
    dropout_v: 0.5
    nb_glimpses: 4
  classif:
    activation: relu
    dropout: 0.5
  dim_q: 2400
  dim_v: 2048
  fusion:
    activation_q: relu
    activation_v: relu
    dim_h: 1200
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 256
  epochs: 70
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_tools
  maxlength: 26
  minwcount: 0
  nans: 14
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
