coco:
  arch: fbresnet152torch
  dir: data/coco
  mode: noatt
logs:
  dir_logs: logs/vqa/mlb_noatt_train
model:
  arch: MLBNoAtt
  classif:
    activation: tanh
    dropout: 0.5
  fusion:
    activation_q: tanh
    activation_v: tanh
    dim_h: 1200
    dim_q: 2400
    dim_v: 2048
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 512
  epochs: 100
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa
  maxlength: 26
  minwcount: 0
  nans: 2000
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
