coco:
  arch: fbresnet152torch
  dir: data/coco
  mode: att
logs:
  dir_logs: logs/vqa2/minhmul_att_train_selu_h200_g8
model:
  arch: MinhmulAtt
  attention:
    activation_mm: selu
    activation_q: selu
    activation_v: selu
    dim_h: 200
    dim_mm: 200
    dim_q: 200
    dim_v: 200
    dropout_mm: 0.5
    dropout_q: 0.5
    dropout_v: 0.5
    nb_glimpses: 8
  classif:
    activation: selu
    dropout: 0.5
  dim_q: 2400
  dim_v: 2048
  fusion:
    activation_q: selu
    activation_v: selu
    dim_h: 200
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 256
  epochs: 130
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA2
  dir: data/vqa2
  maxlength: 26
  minwcount: 0
  nans: 2000
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
