arch: null
batch_size: null
dir_logs: logs/vqa2/mutan_noatt_train
epochs: null
evaluate: false
help_opt: false
learning_rate: null
path_opt: options/vqa2/mutan_noatt_train.yaml
print_freq: 10
resume: ''
save_all_from: null
save_model: true
st_dropout: null
st_fixed_emb: null
st_type: null
start_epoch: 0
vqa_trainsplit: null
workers: 2
