coco:
  arch: resnet152_idrid
  dir: data/raw/idrid
  mode: noatt
  size: 448
logs:
  dir_logs: logs/idrid/minhmul_noatt_train_relu
model:
  arch: MinhmulNoAtt
  classif:
    activation: relu
    dropout: 0.5
  fusion:
    activation_q: relu
    activation_v: relu
    dim_h: 1200
    dim_q: 2400
    dim_v: 2048
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 512
  epochs: 70
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_idrid
  maxlength: 26
  minwcount: 0
  nans: 844
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
