coco:
  arch: resnet152_tools
  dir: data/raw/m2cai16-tool-locations/preprocessed/segmentation
  mode: att
  size: 448
logs:
  dir_logs: logs/tools/mutan_att_train
model:
  arch: MutanAtt
  attention:
    R: 5
    activation_q: tanh
    activation_v: tanh
    dim_hq: 310
    dim_hv: 310
    dim_mm: 510
    dim_q: 310
    dim_v: 310
    dropout_hq: 0
    dropout_hv: 0
    dropout_mm: 0.5
    dropout_q: 0.5
    dropout_v: 0.5
    nb_glimpses: 2
  classif:
    dropout: 0.5
  dim_q: 2400
  dim_v: 2048
  fusion:
    R: 5
    activation_q: tanh
    activation_v: tanh
    dim_hq: 310
    dim_hv: 620
    dim_mm: 510
    dropout_hq: 0
    dropout_hv: 0
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 64
  epochs: 100
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_tools
  maxlength: 26
  minwcount: 0
  nans: 14
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
