logs:
    dir_logs: logs/med/minhmul_att_train_imagenet_h200_g8_relu_bert
vqa:
    dataset: VQA
    dir: data/vqa_med
    trainsplit: train
    nans: 1700
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/raw/vqa_med/preprocessed/
    arch: fbresnet152
    mode: att
    size: 448
model:
    arch: MinhmulAtt
    dim_v: 2048
    dim_q: 768
    seq2vec:
        arch: bert
        dir_st: data/bert
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 8
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: relu
        activation_q: relu
        activation_mm: relu
    fusion:
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: relu
        activation_q: relu
    classif:
        activation: relu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 128
    epochs: 100
