logs:
    dir_logs: logs/med/mutan_att_train_relu_bert_768
vqa:
    dataset: VQA
    dir: data/vqa_med
    trainsplit: train
    nans: 1700
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/raw/vqa_med/preprocessed/
    arch: fbresnet152
    mode: att
    size: 448
model:
    arch: MutanAtt
    dim_v: 2048
    dim_q: 768
    seq2vec:
        arch: bert
        dir_st: data/bert
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 4
        dim_hv: 100
        dim_hq: 100
        dim_mm: 200
        R: 5
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: relu
        activation_q: relu
        dropout_hv: 0
        dropout_hq: 0
    fusion:
        dim_hv: 256
        dim_hq: 100
        dim_mm: 200
        R: 5
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: relu
        activation_q: relu
        dropout_hv: 0
        dropout_hq: 0
    classif:
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 128
    epochs: 100
