logs:
    dir_logs: logs/tools/minhmul_att_train_relu_h200_g4
vqa:
    dataset: VQA
    dir: data/vqa_tools
    trainsplit: train
    nans: 14
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/raw/m2cai16-tool-locations/preprocessed/segmentation
    arch: resnet152_tools
    mode: att
    size: 448
model:
    arch: MinhmulAtt
    dim_v: 2048
    dim_q: 2400
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 4
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: relu
        activation_q: relu
        activation_mm: relu
    fusion:
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: relu
        activation_q: relu
    classif:
        activation: relu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 64
    epochs: 100
