logs:
    dir_logs: logs/vqa/bilinear_att_train_h200_g4_relu
vqa:
    dataset: VQA
    dir: data/vqa
    trainsplit: train
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/coco
    arch: fbresnet152torch
    mode: att
model:
    arch: BilinearAtt
    dim_v: 2048
    dim_q: 2400
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 4
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: relu
        activation_q: relu
        activation_mm: relu
    fusion:
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: relu
        activation_q: relu
    classif:
        activation: relu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 128
    epochs: 100
