logs:
    dir_logs: logs/vqa/minhmul_att_train_selu_h200_g8
vqa:
    dataset: VQA
    dir: data/vqa
    trainsplit: train
    nans: 2000
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/coco
    arch: fbresnet152torch
    mode: att
model:
    arch: MinhmulAtt
    dim_v: 2048
    dim_q: 2400
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 8
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: selu
        activation_q: selu
        activation_mm: selu
    fusion:
        dim_h: 200
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: selu
        activation_q: selu
    classif:
        activation: selu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 128
    epochs: 100
