coco:
  arch: fbresnet152torch
  dir: data/coco
  mode: att
logs:
  dir_logs: logs/vqa/minhmul_att_train_relu
model:
  arch: MinhmulAtt
  attention:
    activation_mm: relu
    activation_q: relu
    activation_v: relu
    dim_h: 1200
    dim_mm: 1200
    dim_q: 1200
    dim_v: 1200
    dropout_mm: 0.5
    dropout_q: 0.5
    dropout_v: 0.5
    nb_glimpses: 4
  classif:
    activation: relu
    dropout: 0.5
  dim_q: 2400
  dim_v: 2048
  fusion:
    activation_q: relu
    activation_v: relu
    dim_h: 1200
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 256
  epochs: 60
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa
  maxlength: 26
  minwcount: 0
  nans: 2000
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
