coco:
  arch: resnet152_breast
  dir: data/raw/breast-cancer/preprocessed/WSI
  mode: att
  size: 448
logs:
  dir_logs: logs/breast/minhmul_att_train_leakyrelu
model:
  arch: MinhmulAtt
  attention:
    activation_mm: leaky_relu
    activation_q: leaky_relu
    activation_v: leaky_relu
    dim_h: 1200
    dim_mm: 1200
    dim_q: 1200
    dim_v: 1200
    dropout_mm: 0.5
    dropout_q: 0.5
    dropout_v: 0.5
    nb_glimpses: 4
  classif:
    activation: leaky_relu
    dropout: 0.5
  dim_q: 2400
  dim_v: 2048
  fusion:
    activation_q: leaky_relu
    activation_v: leaky_relu
    dim_h: 1200
    dropout_q: 0.5
    dropout_v: 0.5
  seq2vec:
    arch: skipthoughts
    dir_st: data/skip-thoughts
    dropout: 0.25
    fixed_emb: false
    type: BayesianUniSkip
optim:
  batch_size: 256
  epochs: 100
  lr: 0.0001
vgenome: null
vqa:
  dataset: VQA
  dir: data/vqa_breast
  maxlength: 26
  minwcount: 0
  nans: 844
  nlp: mcb
  pad: right
  samplingans: true
  trainsplit: train
