logs:
    dir_logs: logs/breast/minhmul_att_train_h600_g4_relu_v3_q2
vqa:
    dataset: VQA
    dir: data/vqa_breast
    trainsplit: train
    nans: 844
    maxlength: 26
    minwcount: 0
    nlp: mcb
    pad: right
    samplingans: True
coco:
    dir: data/raw/breast-cancer/preprocessed/WSI
    arch: resnet152_breast
    mode: att
    size: 448
model:
    arch: MinhmulAtt
    dim_v: 2048
    dim_q: 2400
    centric_v: 3
    centric_q: 2
    seq2vec:
        arch: skipthoughts
        dir_st: data/skip-thoughts
        type: BayesianUniSkip
        dropout: 0.25
        fixed_emb: False
    attention:
        nb_glimpses: 4
        dim_h: 600
        dropout_v: 0.5
        dropout_q: 0.5
        dropout_mm: 0.5
        activation_v: relu
        activation_q: relu
        activation_mm: relu
    fusion:
        dim_h: 600
        dropout_v: 0.5
        dropout_q: 0.5
        activation_v: relu
        activation_q: relu
    classif:
        activation: relu
        dropout: 0.5
optim:
    lr: 0.0001
    batch_size: 64
    epochs: 100